### ISSUE TITLE
Redesign the project structure

### ISSUE THREAD

**Issue by marnandr** [marnandr/SoftwareTestingProject#10]
The not well designed project structure need to be redesigned. For the job will be responsible me and @M-Soudani . In a personal meeting we will solve the presented problems.

**Comment by judit0310** [comment]
The previous (#9 ) issue could be continued instead of this new issue. 
@marnandr you could write a comment, and then assign the collaborators.
There is currently two issue for the same problem.

**Comment by marnandr** [comment]
I don't realize the last issue. Sorry for the misunderstanding.
