### ISSUE TITLE
Sequence diagram design

### ISSUE THREAD

**Issue by marnandr** [marnandr/SoftwareTestingProject#11]
Before we start the coding of the model module we need to design the sequence diagram.
@M-Soudani will present the first example of the diagram then the jobs will be sorted among:
@M-Soudani: ListCourses(Student), CreateARequest(Student), ListFrom(Student).
@marnandr: CheckRequestStatus(Student), Complain(Student), ListRequest(Teacher), ForwardRequest(Teacher).
@Anrit: ListRequest(Administrator), ManageFormTypes(Administrator).
@urgyanmiki: ManageComplains(Administrator).

**Comment by M-Soudani** [comment]
Hello Team,
Please find the create request sequence diagram.
Thanks
![create request sequence diagram](https://user-images.githubusercontent.com/17377824/46234454-a82ed980-c376-11e8-96af-012683a6149c.JPG)

**Comment by Anrit** [comment]
Hi! 
Here is the sequence diagram for the ListRequest(Administrator) and ManageFormTypes(Administrator).

![untitled diagram](https://user-images.githubusercontent.com/32998695/46258420-a24a0d00-c4ca-11e8-8131-19fd65abfa7f.png)

**Comment by urgyanmiki** [comment]
Hi!
This is the sequence diagram of the complains 
[
![sequencediagramcomplain](https://user-images.githubusercontent.com/43173169/46259410-62d6ed00-c4d9-11e8-9601-8e067b033799.jpg)
](url)

**Comment by urgyanmiki** [comment]
This is the ManageComplains sequence diagram
![managecomplains](https://user-images.githubusercontent.com/43173169/46259491-70d93d80-c4da-11e8-847b-e0d871206cb1.jpg)
