### ISSUE TITLE
Activity diagram design

### ISSUE THREAD

**Issue by marnandr** [marnandr/SoftwareTestingProject#12]
Before we start the coding of the model module we need to design the activity diagram too.
For this task @vaszabi @PapDani @DavidCintia will be responsible.
@M-Soudani will lead your senior leader if you got any question about this task please get contact with him.
The job will be separated to:
1. Student: @vaszabi 
2. Teacher: @DavidCintia 
3. Administrator: @PapDani 
Good Luck!

**Comment by M-Soudani** [comment]
Hello Team,
Please find the Student Activity Diagram.
Thanks
![struden activity diagram](https://user-images.githubusercontent.com/17377824/46230939-76b01100-c36a-11e8-9c3e-1b6ae030f46f.jpg)

**Comment by PapDani** [comment]
I have created this activity diagram for the 'administrator'. I hope it's good. If not, please let me know.

![activity dia for administrator 01](https://user-images.githubusercontent.com/43150057/46233193-11601e00-c372-11e8-9bbc-471cb22f012f.jpg)

**Comment by DavidCintia** [comment]
Hello Everyone, here is the last  Activity Diagram for the Teacher.

![teacheractivitydiagram](https://user-images.githubusercontent.com/43182060/46247948-2b057200-c413-11e8-8c14-f3993ae5779a.jpeg)
