### ISSUE TITLE
The design of the Database.

### ISSUE THREAD

**Issue by marnandr** [marnandr/SoftwareTestingProject#7]
Dear Team Members,
Your milestone will be the design of our future database.
The database design has three stages the first two will be your responsibility:
1, The design of the ER model
2, The creation of the relational schema
The professional leading will be @M-Soudani 's task.

**Comment by M-Soudani** [comment]
Hello Team,
Please find the attached ER-Diagram, willing to hear your feedback to improve any missing issues from my side. Thanks.

![er diagram](https://user-images.githubusercontent.com/17377824/45931714-ff493e80-bf71-11e8-962e-b3b30d071121.png)

**Comment by marnandr** [comment]
Perfect work.
