### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by judit0310** [marnandr/SoftwareTestingProject#9]
[projectStructure-eps-converted-to.pdf](https://github.com/marnandr/SoftwareTestingProject/files/2419727/projectStructure-eps-converted-to.pdf)

**Comment by judit0310** [comment]
The current structure is not the one on the attached pdf, which was presented on the last lecture.

**Comment by marnandr** [comment]
The not well designed project structure need to be redesigned. For the job will be responsible me and @M-Soudani . In a personal meeting we will solve the presented problems.

**Comment by marnandr** [comment]
Project structure successfully repaired.
